name: Monthly PR metrics
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: PR metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read

    steps:
      - name: Get date for last 30 days
        shell: bash
        run: |
          # Calculate the date 30 days ago
          start_date=$(date -d "30 days ago" +%Y-%m-%d)

          #Set an environment variable with the date
          echo "start_date=$start_date" >> "$GITHUB_ENV"

      - name: Get PR metrics
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_QUERY: 'repo:${{ github.repository }} is:pr created:>=${{ env.start_date }}'

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Monthly PR metrics report (dev)
          content-filepath: ./issue_metrics.md